# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 590b5909f39b567ee350667522653d2c057213e69def2cab3461e4e9ea5890aef1f260e5ce7909af4a1e97dec04cb6f0dabd0a6b1b975689782f880c7d468235

test:
  secret_key_base: c5f7975d1daadc68c2c2dd57b4ce27ab95e3ccfdb52c075d60cb39be5b61157e4fc6e4c45e26085cb77cdb86edb040914f9f0d1f7e59b9f18ae5e35fb1309f6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
